# 1. 기본 통계 데이터를 계산하기
 ## (1) 평균 계산하기
 ## (2) 배열을 활용한 평균, 표준편차, 중앙값 계산
 
 
# 2. Numpy로 모든 걸 한방에!
 ## (1) NumPy 소개
 Numerical Python의 줄임말로, 과학 계산용 고성ㄴ능 컴퓨팅과 데이터 분석에 필요한 파이썬 패키지이다.

### numpy의 장점
- 빠르고 효율적으로 사용하여 벡터의 산술 연산과 브로드캐스팅 연산을 지원하는 다차원 배열 `ndarray`데이터 타입을 지원한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 다양한 표준 수학 함수를 제공한다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있다.(= 파일로 저장한다)
- 선형대수, 난수발생기, 푸리에 변환 가능, C/C++ 포트란으로 쓰인 코드를 통합한다.

 ## (2) NumPy 주요 기능
 ### 1) ndarray 만들기
 ndarray 객체를 이용하면 파이썬에서 사용하는 대규모 데이터 집합을 n차원 배열로 담을 수 있다.
  - `arange()`와 `arrary([])`로 만들 수 있다.

In [1]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print("--------------------------")
print(B)
print(type(B))
print("--------------------------")
print(C)
print(type(C))
print("--------------------------")
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>


numpy.ndarrary도 array이기 때문에, **모든 element의 type이 동일해야 한다.**

### 2) 크기
- `ndarray.size`
- `ndarray.shape`
- `ndarray.ndim`
- `reshape()`

In [3]:
A = np.arange(10).reshape(2, 5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print("행렬 내 원소의 개수:", A.size)
print("행렬의 모양:", A.shape)
print("행렬의 축 개수:", A.ndim)

행렬 내 원소의 개수: 10
행렬의 모양: (2, 5)
행렬의 축 개수: 2


### 3) type
NumPy 라이브러리 내부의 자료형들은 파이썬 내장함수와 동일하다.
그러나 헷갈리는 기능이 하나 있을텐데, 바로 `type()`과 `dtype()` 메서드이다.

- Numpy: `numpy.array.dtype`
- 파이썬: `type()`